# nginx.conf
events {
    worker_connections 1024;
}

http {
    upstream ml_api {
        least_conn;
        server api:8000;
        # Add more api instances for scaling
        # server api2:8000;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://ml_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /mlflow {
            proxy_pass http://mlflow-server:5000;
            proxy_set_header Host $host;
        }
    }
}